services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
     - ./dynamodb:/home/dynamodblocal/data
    # working_dir: /home/dynamodblocal
    environment:
      AWS_REGION: "eu-central-1"
    ports:
      - "8000:8000"
    # healthcheck:
    #   test: [ "CMD-SHELL", "curl -v http://dynamodb-local :8000" ]
    #   interval: 3s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 3s
    restart: always

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "eu-central-1"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local
        # condition: service_healthy